# Simple OS – lightdm-gtk-greeter
[greeter]
background=/usr/share/backgrounds/simpleos/wallpaper.png
user-background=false
theme-name=Arc-Dark
icon-theme-name=Papirus-Dark
cursor-theme-name=Adwaita
font-name=Inter 11
xft-antialias=true
xft-hintstyle=hintslight
xft-rgba=rgb
indicators=~host;~spacer;~clock;~spacer;~session;~a11y;~power
clock-format=%a, %b %-d   %H:%M
position=50%,center 50%,center
screensaver-timeout=60
