[*]
wallpaper_mode=crop
wallpaper_common=1
wallpaper=/usr/share/backgrounds/simpleos/wallpaper.png
desktop_bg=#1e1e2e
desktop_fg=#cdd6f4
desktop_shadow=#11111b
desktop_font=Inter 10
# Rechtsklick auf den Desktop -> Openbox-Menü statt pcmanfm-Menü
show_wm_menu=1
show_documents=0
show_trash=0
show_mounts=0
